apiVersion: apps/v1
kind: Deployment
metadata:
  name: PROJECT-pod
  namespace: PROJECT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PROJECT
  template:
    metadata:
      labels:
        app: PROJECT
    spec:
      containers: 
        - name: PROJECT-mysql
          image: <MYSQLIMAGE>
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test123
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: PROJECT-mysql-pvc


            